[package]
name = "genfile"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
human-size = "0.4.3"
indicatif = "0.17.8"
rand = "0.8.5"
rayon = "1.10.0"
