[package]
edition = "2021"
name = "genfile"
version = "0.1.0"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
indicatif = "0.17"
rand = { version = "0.9", features = ["nightly", "simd_support"] }
rayon = "1.10"
thiserror = "2.0"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "unwind"
